version: 0.0
os: linux
files:
  - source: /
    destination: /home/bitnami/app
hooks:
  BeforeInstall:
    - location: scripts/preinstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/postinstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root