#!/usr/bin/env bash
# Copy kafka-1.3.5.tar.gz to the lib/Py directory
set -e
PY_DIR='../lib/Py'
if [ ! -d "$PY_DIR" ]; then
  mkdir -p "$PY_DIR" 
fi
curl -o "$PY_DIR"/kafka_Py https://files.pythonhosted.org/packages/3b/1b/44605e699e0970a2be3d7135d185f95e8605399aa0f2a9d64de342eae4b7/kafka-1.3.5.tar.gz 
unset -v PY_DIR
